//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichMyCare.EnrichMyCareService.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnrichMyCare_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnrichMyCare_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnrichMyCare.EnrichMyCareService.Infrastructure.EnrichMyCare_Messages", typeof(EnrichMyCare_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excercise Id having null value.
        /// </summary>
        internal static string ExcerciseIdIsNull {
            get {
                return ResourceManager.GetString("ExcerciseIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image/Video successfully deleted from the data store.
        /// </summary>
        internal static string ImageVideoDeletedById {
            get {
                return ResourceManager.GetString("ImageVideoDeletedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageVideo Id having null value.
        /// </summary>
        internal static string ImageVideoIdIsNull {
            get {
                return ResourceManager.GetString("ImageVideoIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image/Video by given Excercise Id not found.
        /// </summary>
        internal static string ImageVideoNotFoundByExcerciseId {
            get {
                return ResourceManager.GetString("ImageVideoNotFoundByExcerciseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image/Video by given ImageVideo Id not found.
        /// </summary>
        internal static string ImageVideoNotFoundById {
            get {
                return ResourceManager.GetString("ImageVideoNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image/Video file has invalid extension.
        /// </summary>
        internal static string InvalidExtension {
            get {
                return ResourceManager.GetString("InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Id having null value.
        /// </summary>
        internal static string PatientIdIsNull {
            get {
                return ResourceManager.GetString("PatientIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Id having null value.
        /// </summary>
        internal static string ProgramIdIsNull {
            get {
                return ResourceManager.GetString("ProgramIdIsNull", resourceCulture);
            }
        }
    }
}
